#!bin/bash
echo "jenjins and git source code management tool"
else "not jenkins"
hello
iam learning the git and git hub and git hub copolite
kubernetes
terraform
ansible
argocd
grafana
monitoring
tools
tobe
SRE site Reliability Engineer
development engineer  value operation present solutions
devOps
devscOps
Aiops

